version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # AMQP connection port
      - "15672:15672"  # Management UI
    networks:
      - spring-react-network

  # PostgreSQL Database for Microservice 1
  postgres-db1:
    image: postgres:13
    container_name: postgres-db1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app1
    ports:
      - "5433:5432"  
    networks:
      - spring-react-network
    volumes:
      - postgres-data1:/var/lib/postgresql/data

  # PostgreSQL Database for Microservice 2
  postgres-db2:
    image: postgres:13
    container_name: postgres-db2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app2
    ports:
      - "5434:5432" 
    networks:
      - spring-react-network
    volumes:
      - postgres-data2:/var/lib/postgresql/data

  # PostgreSQL Database for Microservice 3
  postgres-db3:
    image: postgres:13
    container_name: postgres-db3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app3
    ports:
      - "5435:5432" 
    networks:
      - spring-react-network
    volumes:
      - postgres-data3:/var/lib/postgresql/data

  # Spring Boot Microservice 1 (User Service)
  microservice1:
    build:
      context: ./users 
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db1:5432/app1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres-db1
    ports:
      - "8080:8080" 
    networks:
      - spring-react-network

  # Spring Boot Microservice 2 (Devices Service)
  microservice2:
    build:
      context: ./devices  
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db2:5432/app2
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres-db2
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - spring-react-network

  microservice3:
    build:
      context: ./measurement  
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db3:5432/app3
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres-db3
      - rabbitmq
    ports:
      - "8082:8082"
    networks:
      - spring-react-network

  # React Frontend
  react-app:
    build:
      context: ./Frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expose port for React app
    networks:
      - spring-react-network

networks:
  spring-react-network:
    driver: bridge

volumes:
  postgres-data1:
  postgres-data2:
  postgres-data3: